spring.application.name=activity-manager

spring.datasource.url=jdbc:mysql://localhost:3306/activity_manager
spring.datasource.username=root
spring.datasource.password=Ma48!@ztu
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
